### ISSUE TITLE
Deprecation message DS.FixtureAdapter has been deprecated

### ISSUE THREAD

**Issue by adam-knights** [switchfly/ember-test-helpers#64]
Using Ember 1.13.2 and Ember Data 1.13.2 I get deprecation message when running http://localhost:4200/tests

DEPRECATION: DS.FixtureAdapter has been deprecated and moved into an unsupported addon: https://github.com/emberjs/ember-data-fixture-adapter/tree/master
        at Ember.defineProperty.get (http://localhost:4200/assets/vendor.js:86516:19)
        at exports.default.TestModule.default.extend.setupModel (http://localhost:4200/assets/test-support.js:2151:53)
        at nextStep (http://localhost:4200/assets/test-support.js:2280:53)
        at tryCatch (http://localhost:4200/assets/vendor.js:65295:14)
        at invokeCallback (http://localhost:4200/assets/vendor.js:65310:15)
        at http://localhost:4200/assets/vendor.js:67095:40
        at http://localhost:4200/assets/vendor.js:42094:7
        at Queue.invoke (http://localhost:4200/assets/vendor.js:11455:16)
        at Object.Queue.flush (http://localhost:4200/assets/vendor.js:11519:11)

Seems to be at line 21 of https://github.com/switchfly/ember-test-helpers/blob/master/lib/ember-test-helpers/test-module-for-model.js.

More specifically, if I re-run a standard generated 'it exists' unit test on a model through specific url such as http://localhost:4200/tests?testId=50b08f2a, then I also see the deprecation.

**Comment by quaertym** [comment]
I ran into this today as well.

**Comment by johnnyshields** [comment]
+1 to resolving this and other deprecations

**Comment by rwjblue** [comment]
This issue was resolved in https://github.com/switchfly/ember-test-helpers/commit/d8c0b4e41cc178fd6e9d273e6eb1c566053696b3 which has been available since ember-test-helpers@0.5.2 (and ember-qunit@0.4.2).

@johnnyshields - Please report any deprecations that are being triggered by ember-test-helpers.  There should be none.
