### ISSUE TITLE
Deprecation message You tried to look up 'store:main', but this has been deprecated in favor of 'service:store'

### ISSUE THREAD

**Issue by adam-knights** [switchfly/ember-test-helpers#65]
Using Ember 1.13.2 and Ember Data 1.13.2 I get this deprecation message when running http://localhost:4200/tests.

DEPRECATION: You tried to look up 'store:main', but this has been deprecated in favor of 'service:store'.
        at ember$data$lib$system$container$proxy$$ContainerProxy.registerDeprecation.preLookupCallback (http://localhost:4200/assets/vendor.js:77620:15)
        at Object.ember$data$lib$system$container$proxy$$ContainerProxy.aliasedFactory.create (http://localhost:4200/assets/vendor.js:77604:13)
        at instantiate (http://localhost:4200/assets/vendor.js:11998:24)
        at lookup (http://localhost:4200/assets/vendor.js:11865:17)
        at Object.Container.lookup (http://localhost:4200/assets/vendor.js:11797:14)
        at http://localhost:4200/assets/test-support.js:2165:30
        at Object.Backburner.run (http://localhost:4200/assets/vendor.js:10776:25)
        at Object.run (http://localhost:4200/assets/vendor.js:29984:27)
        at exports.default.TestModule.default.extend.setupModel.callbacks.subject (http://localhost:4200/assets/test-support.js:2164:35)

Seems to be coming from line 35 of https://github.com/switchfly/ember-test-helpers/blob/master/lib/ember-test-helpers/test-module-for-model.js, but line 27 may also be of interest to this issue.

More specifically I see this deprecation in a standard generated 'it exists' unit model test, at URL such as http://localhost:4200/tests?testId=50b08f2a.

**Comment by rwjblue** [comment]
Thank you for reporting, I'll confirm with the Ember Data team, but I believe that we will need to detect version and register the right thing.

**Comment by adam-knights** [comment]
Is this also now resolved like https://github.com/switchfly/ember-test-helpers/issues/64? By https://github.com/switchfly/ember-test-helpers/commit/d8c0b4e41cc178fd6e9d273e6eb1c566053696b3?

**Comment by quaertym** [comment]
Fixed by https://github.com/switchfly/ember-test-helpers/pull/74

**Comment by rwjblue** [comment]
Yep, thanks @quaertym!
